(function(){function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof l&&l];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this);function ea(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
ea("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
ea("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=da[b[c]];typeof d==="function"&&typeof d.prototype[a]!="function"&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(aa(this))}})}return a});function fa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function ha(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}ea("Array.prototype.keys",function(a){return a?a:function(){return ha(this,function(b){return b})}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var ia=this||self;function ja(a){var b=typeof a;return b!="object"?b:a?Array.isArray(a)?"array":b:"null"}function ka(a,b){function c(){}c.prototype=b.prototype;a.Y=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.X=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}}function la(a){return a};function ma(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,ma);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b)}ka(ma,Error);ma.prototype.name="CustomError";function na(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");ma.call(this,c+a[d])}ka(na,ma);na.prototype.name="AssertionError";function oa(a,b){throw new na("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var pa;function qa(){if(pa===void 0){var a=null,b=ia.trustedTypes;if(b&&b.createPolicy){try{a=b.createPolicy("goog#html",{createHTML:la,createScript:la,createScriptURL:la})}catch(c){ia.console&&ia.console.error(c.message)}pa=a}else pa=a}return pa};function ra(a,b){if(b!==sa)throw Error("TrustedResourceUrl is not meant to be built directly");this.g=a}ra.prototype.toString=function(){return this.g+""};var sa={};/*

 SPDX-License-Identifier: Apache-2.0
*/
var ta={};function ua(){if(ta!==ta)throw Error("Bad secret");};function wa(a){ua();this.g=a}wa.prototype.toString=function(){return this.g};new wa("about:blank");new wa("about:invalid#zClosurez");var xa=[];function ya(a){console.warn("A URL with content '"+a+"' was sanitized away.")}xa.indexOf(ya)===-1&&xa.push(ya);function za(){ua()}za.prototype.toString=function(){return""};function Aa(){ua()}Aa.prototype.toString=function(){return""};new za;new Aa;var Ba={};function Ca(a,b){if(b!==Ba)throw Error("SafeHtml is not meant to be built directly");this.g=a}Ca.prototype.toString=function(){return this.g.toString()};new Ca(ia.trustedTypes&&ia.trustedTypes.emptyHTML||"",Ba);function Da(a,b){if(a.nodeType===1){var c=a.tagName;if(c==="SCRIPT"||c==="STYLE")throw Error(c==="SCRIPT"?"Use safeScriptEl.setTextContent with a SafeScript.":"Use safeStyleEl.setTextContent with a SafeStyleSheet.");}b instanceof Ca&&b.constructor===Ca?b=b.g:(oa("expected object of type SafeHtml, got '"+b+"' of type "+ja(b)),b="type_error:SafeHtml");a.innerHTML=b};function Ea(a,b){b instanceof ra&&b.constructor===ra?b=b.g:(oa("expected object of type TrustedResourceUrl, got '%s' of type %s",b,ja(b)),b="type_error:TrustedResourceUrl");a.src=b;var c,d;(c=(b=(d=(c=(a.ownerDocument&&a.ownerDocument.defaultView||window).document).querySelector)==null?void 0:d.call(c,"script[nonce]"))?b.nonce||b.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",c)};function Fa(a){a=Ga(a);if(typeof a!=="string")throw Error("Expected a string");var b=qa();a=b?b.createHTML(a):a;return new Ca(a,Ba)}function Ha(a){a=Ga(a);if(typeof a!=="string")throw Error("Expected a string");var b=qa();a=b?b.createScriptURL(a):a;return new ra(a,sa)}function Ga(a){return a===null?"null":a===void 0?"undefined":a};function n(a,b,c){var d=Array.prototype.slice.call(arguments,2);return function(){var e=d.slice();e.push.apply(e,arguments);return a.apply(b,e)}}function Ia(a,b){if(a){var c=Array.prototype.slice.call(arguments,1);try{return a.apply(null,c)}catch(d){return d}}}function p(a,b){if(document.createEvent){var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!0,!0,b);return document.dispatchEvent(c)}return!0}
var q=window.performance&&window.performance.timing&&window.performance.now?function(){return window.performance.timing.navigationStart+window.performance.now()}:function(){return(new Date).getTime()};function Ja(){};function r(a,b){if(a.forEach)a.forEach(b,void 0);else for(var c=0,d=a.length;c<d;c++)c in a&&b.call(void 0,a[c],c,a)}function Ka(a,b){if(a.every)return a.every(b,void 0);for(var c=0,d=a.length;c<d;c++)if(c in a&&!b.call(void 0,a[c],c,a))return!1;return!0}function La(a,b){if(a.some)return a.some(b,void 0);for(var c=0,d=a.length;c<d;c++)if(c in a&&b.call(void 0,a[c],c,a))return!0;return!1}
function Ma(a,b){if(a.filter)return a.filter(b,void 0);var c=[];r(a,function(d,e,f){b.call(void 0,d,e,f)&&c.push(d)});return c}function Na(a,b){if(a.map)return a.map(b,void 0);var c=[];c.length=a.length;r(a,function(d,e,f){c[e]=b.call(void 0,d,e,f)});return c}function v(a){return Object.prototype.toString.call(a)=="[object Array]"?a:[a]};function w(a,b){return x[a]=b}var x=window._spf_state||{};window._spf_state=x;function y(a,b){var c=a.length-b.length;return c>=0&&a.indexOf(b,c)==c}function Oa(a){return Object.prototype.toString.call(a)=="[object String]"}var Pa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s+|\s+$/g,"")};function z(a,b){a=a.split(b);var c=a.length==1;return[a[0],c?"":b,c?"":a.slice(1).join(b)]}function Qa(){return"spfName".replace(/([A-Z])/g,"-$1").toLowerCase()};function Ra(a){a.data&&Oa(a.data)&&a.data.lastIndexOf("spf:",0)==0&&Sa(a.data.substring(4))}function Sa(a){var b=Ta[a];b&&(delete Ta[a],b())}function Ua(a){window.addEventListener?window.addEventListener("message",a,!1):window.attachEvent&&window.attachEvent("onmessage",a)}function Va(a){window.removeEventListener?window.removeEventListener("message",a,!1):window.detachEvent&&window.detachEvent("onmessage",a)}
var Wa=function(){function a(){b=!1}if(!window.postMessage)return!1;var b=!0;Ua(a);window.postMessage("","*");Va(a);return b}(),Ta={};"async-defers"in x||w("async-defers",Ta);Ta=x["async-defers"];Wa&&("async-listener"in x&&Va(x["async-listener"]),Ua(Ra),w("async-listener",Ra));var Xa={"animation-class":"spf-animate","animation-duration":425,"cache-lifetime":6E5,"cache-max":50,"cache-unified":!1,"link-class":"spf-link","nolink-class":"spf-nolink","navigate-limit":20,"navigate-lifetime":864E5,"reload-identifier":null,"request-timeout":0,"url-identifier":"?spf=__type__"},A={};"config"in x||w("config",A);A=x.config;function Ya(a){var b=D();a in b&&delete b[a]}function $a(){var a=D();for(b in a)ab(a[b])||delete a[b];a=D();var b=parseInt(A["cache-max"],10);b=isNaN(b)?Infinity:b;b=Object.keys(a).length-b;if(!(b<=0))for(var c=0;c<b;c++){var d=Infinity,e;for(e in a)if(a[e].count<d){var f=e;d=a[e].count}delete a[f]}}function ab(a){if(!(a&&"data"in a))return!1;var b=a.life;b=isNaN(b)?Infinity:b;a=a.time;return q()-a<b}function bb(a){var b=parseInt(x["cache-counter"],10)||0;b++;w("cache-counter",b);a.count=b}
function D(a){return!a&&"cache-storage"in x?x["cache-storage"]:w("cache-storage",a||{})};function cb(a){return a.classList?a.classList:a.className&&a.className.match(/\S+/g)||[]}function db(a,b){if(b){if(a.classList)return a.classList.contains(b);a=cb(a);return La(a,function(c){return c==b})}return!1}function E(a,b){b&&(a.classList?a.classList.add(b):db(a,b)||(a.className+=" "+b))}function F(a,b){if(b)if(a.classList)a.classList.remove(b);else{var c=cb(a);c=Ma(c,function(d){return d!=b});a.className=c.join(" ")}};function eb(a){var b=document.body;b.dataset?b.dataset.spfName=a:b.setAttribute("data-"+Qa(),a)};function fb(a,b){b=b||document;return b.querySelectorAll?b.querySelectorAll(a):[]}function gb(a,b,c){for(;a;){if(b(a))return a;if(c&&a==c)break;a=a.parentNode}return null}function hb(a,b,c){b=b||document;var d=b.createElement("iframe");d.id=a||"";d.src='javascript:""';d.style.display="none";c&&(d.onload=n(c,null,d));b.body.appendChild(d);return d};function ib(a,b,c){var d=null,e=window.history.state;if(e){d={};for(var f in e)d[f]=e[f]}if(b)for(f in d=d||{},b)d[f]=b[f];jb(!0,a,d,c)}function jb(a,b,c,d){if(b||c){b=b||window.location.href;c=c||{};var e=q();w("history-timestamp",e);c["spf-timestamp"]=e;if(a)kb(c,b);else if(a=lb().contentWindow.history.pushState,typeof a=="function")a.call(window.history,c,"",b);else throw Error("history.pushState is not a function.");w("history-url",b);d&&(d=x["history-callback"])&&d(b,c)}}
function mb(a){var b=window.location.href;if(x["history-ignore-pop"])w("history-ignore-pop",!1);else if(a.state){a=a.state;var c=a["spf-timestamp"];b==x["history-url"]?(w("history-timestamp",c),kb(a,b)):(a["spf-back"]=c<parseInt(x["history-timestamp"],10),a["spf-current"]=x["history-url"],w("history-timestamp",c),w("history-url",b),(c=x["history-callback"])&&c(b,a))}}
function kb(a,b){var c=lb().contentWindow.history.replaceState;if(typeof c=="function")c.call(window.history,a,"",b);else throw Error("history.replaceState is not a function");}function lb(){var a=document.getElementById("history-iframe");a||(a=hb("history-iframe"));return a};function nb(a,b){a&&b&&(a in G||(G[a]=[]),G[a].push(b))}function ob(a,b){a in G&&b&&Ka(G[a],function(c,d,e){return c==b?(e[d]=null,!1):!0})}function pb(a){a in G&&r(G[a],function(b,c,d){d[c]=null;b&&b()})}var G={};"ps-s"in x||w("ps-s",G);G=x["ps-s"];function J(a,b,c){var d=K[a];return a&&b?(d||(d=K[a]={items:[],A:0,v:0,G:1}),d.items.push({I:b,delay:c||0})):d&&d.items.length||0}function L(a,b){var c=K[a];if(c){var d=!!c.A||!!c.v;c.G>0&&(b||!d)&&qb(a,b)}}function rb(a){(a=K[a])&&a.G--}function sb(a,b){var c=K[a];c&&(c.G++,L(a,b))}function tb(a){var b=K[a];b&&(ub(b),delete K[a])}
function qb(a,b){var c=K[a];if(c&&(ub(c),c.G>0&&c.items.length)){var d=c.items[0];d&&(a=n(function(e,f){f();e()},null,n(qb,null,a,b)),b?(c.items.shift(),a(d.I)):vb(c,d,a))}}function vb(a,b,c){b.delay?(c=n(c,null,Ja),a.v=setTimeout(c,b.delay),b.delay=0):(a.items.shift(),c=n(c,null,b.I),(b=(b=A["advanced-task-scheduler"])&&b.addTask)?a.A=b(c):a.v=setTimeout(c,0))}function ub(a){if(a.A){var b=A["advanced-task-scheduler"];(b=b&&b.cancelTask)&&b(a.A);a.A=0}a.v&&(clearTimeout(a.v),a.v=0)}var K={};function wb(a){var b=document.createElement("a");b.href=a;b.href=b.href;a={href:b.href,protocol:b.protocol,host:b.host,hostname:b.hostname,port:b.port,pathname:b.pathname,search:b.search,hash:b.hash,username:b.username,password:b.password};a.origin=a.protocol+"//"+a.host;a.pathname&&a.pathname[0]=="/"||(a.pathname="/"+a.pathname);return a}function N(a,b){a=wb(a);return b?a.href:z(a.href,"#")[0]}
function xb(a,b){var c=z(a,"#");a=c[0];r(b,function(d){a=a.replace(new RegExp("([?&])"+d+"(?:=[^&]*)?(?:(?=[&])|$)","g"),function(e,f){return f=="?"?f:""})});y(a,"?")&&(a=a.slice(0,-1));return a+c[1]+c[2]}function yb(a){var b=A["advanced-persistent-parameters"]||"",c=z(a,"#");a=c[0];var d=a.indexOf("?")!=-1?"&":"?";a+=b?d+b:"";return a+c[1]+c[2]};/*

 SPF
 (c) 2012-2017 Google Inc.
 https://ajax.googleapis.com/ajax/libs/spf/2.4.0/LICENSE
*/
function zb(a,b,c,d){var e=a=="js";b=O(a,b);var f=c||"^"+b,g=P(a,f),h;c&&(h=Q[P(a,c)])&&b!=h&&(p(e?"spfjsbeforeunload":"spfcssbeforeunload",{name:c,url:h}),e=h,delete Q[P(a,c)],e&&delete S[P(a,e)],delete G[P(a,c)],nb(g,n(Ab,null,a,c,h)));if((e=S[P(a,b)])&&f!=e){delete Q[P(a,e)];delete S[P(a,b)];var k=P(a,e);k&&g&&k in G&&(G[g]=(G[g]||[]).concat(G[k]),delete G[k])}S[P(a,b)]=f;Q[P(a,f)]=b;nb(g,d);d=n(Bb,null,a);T[P(a,b)]?(e&&f!=e&&(a=Cb(a,b))&&a.setAttribute("name",c||""),d()):(a=Db(a,b,d,void 0,void 0,
h))&&c&&a.setAttribute("name",c)}function Eb(a,b){var c=Q[P(a,b)];delete Q[P(a,b)];c&&delete S[P(a,c)];delete G[P(a,b)];Ab(a,b,c)}function Ab(a,b,c){c&&(p(a=="js"?"spfjsunload":"spfcssunload",{name:b,url:c}),Fb(a,c))}function Bb(a){var b=P(a,""),c;for(c in G)c.indexOf(b)==0&&Ka(c.substring(b.length).split("|"),n(Gb,null,a))&&pb(c)}
function Db(a,b,c,d,e,f){function g(){T[P(a,b,e)]&&(T[P(a,b,e)]=2);h&&m&&m.parentNode&&k==document&&m.parentNode.removeChild(m);c&&setTimeout(c,0);return null}var h=a=="js";b=O(a,b);T[P(a,b,e)]=1;var k=d||document,m=k.createElement(h?"script":"link");if(!b)return g();d=Hb(b);m.className=P(a,d);"onload"in m?m.onerror=m.onload=g:m.onreadystatechange=function(){/^c|loade/.test(m.readyState)&&g()};d=k.getElementsByTagName("head")[0]||k.body;h?(m.async=!0,Ea(m,Ha(b)),d.insertBefore(m,d.firstChild)):(m.rel=
"stylesheet",m.href=b,(f=f?Cb(a,f,d):null)?d.insertBefore(m,f):d.appendChild(m));return m}function Fb(a,b){b=O(a,b);var c=Cb(a,b);c&&c.parentNode&&c.parentNode.removeChild(c);delete T[P(a,b)]}function Cb(a,b,c){b=Hb(b);return fb("."+P(a,b),c)[0]}function Ib(a){var b=a=="js",c=[];r(fb(b?"script[src]":'link[rel~="stylesheet"]'),function(d){var e=b?d.src:d.href;e=O(a,e);if(!T[P(a,e)]){T[P(a,e)]=2;var f=Hb(e);E(d,P(a,f));if(f=d.getAttribute("name"))S[P(a,e)]=f,Q[P(a,f)]=e;c.push(d)}})}
function Jb(a,b,c){if(b&&(b=O(a,b),c||!T[P(a,b)]))if(c&&a=="img")Kb(b);else{var d=Hb(b),e=P(a,d),f=P(a,"prefetch");d=document.getElementById(f);if(!d)d=hb(f,null,function(g){g.title=f;L(f,!0)});else if(!c&&d.contentWindow.document.getElementById(e))return;a=n(Lb,null,d,a,b,e,f);d.title?a():J(f,a)}}
function Lb(a,b,c,d,e){var f=b=="js",g=b=="css";a=a.contentWindow.document;var h=a.getElementById(d);h&&h.parentNode.removeChild(h);f?(h=a.createElement("object"),Mb?a.createElement("script").src=c:h.data=c,h.id=d,a.body.appendChild(h)):g?(h=Db(b,c,null,a,e),h.id=d):(h=a.createElement("img"),Mb&&(c=c+"#"+q()),h.src=c,h.id=d,a.body.appendChild(h))}function Kb(a){var b=new Image;Mb&&(a=a+"#"+q());b.src=a}
function Nb(a,b,c){var d=a=="js",e=Q[P(a,c)],f=b.replace(/\s/g,"");f=f||"";for(var g=0,h=0,k=f.length;h<k;++h)g=31*g+f.charCodeAt(h),g%=4294967296;f="hash-"+g;Q[P(a,c)]=f;!Ob(a,f)&&(b=Pb(a,b))&&(T[P(a,f)]=2,b&&!d&&(d=Hb(f),b.className=P(a,d),b.setAttribute("name",c)),(e=e&&e[0])&&Fb(a,e))}
function Pb(a,b){b=Pa(b);if(!b)return null;var c=document.getElementsByTagName("head")[0]||document.body;a=="js"?(a=document.createElement("script"),a.text=b,c.appendChild(a),c.removeChild(a)):(a=document.createElement("style"),c.appendChild(a),"styleSheet"in a?a.styleSheet.cssText=b:a.appendChild(document.createTextNode(b)));return a}
function O(a,b){var c="rsrc-p-"+a;if(b){var d=b.indexOf("//");if(d<0){if(b.lastIndexOf("hash-",0)==0)return b;c=x[c]||"";if(Oa(c))b=c+b;else for(var e in c)b=b.replace(e,c[e]);a!="img"&&(b=b.indexOf("."+a)<0?b+"."+a:b);b=N(b)}else d==0&&(b=N(b))}return b}function P(a,b,c){return a+"-"+b+(c?"-"+c:"")}function Hb(a){return a?String(a).replace(/[^\w]/g,""):""}function Ob(a,b){a=T[P(a,b)];return b==""||a==2}function Gb(a,b){b=Q[P(a,b)];return b!=void 0&&Ob(a,b)}
var T={},S={},Q={},Mb=navigator.userAgent.indexOf(" Trident/")!=-1;"rsrc-s"in x||w("rsrc-s",T);T=x["rsrc-s"];"rsrc-n"in x||w("rsrc-n",S);S=x["rsrc-n"];"rsrc-u"in x||w("rsrc-u",Q);Q=x["rsrc-u"];function Qb(a){a=v(a);r(a,function(b){Jb("img",b,!0)})};function Rb(a,b,c){zb("js",a,b,c)}function Sb(a){Eb("js",a)}function Tb(a,b){Db("js",a,b)}function Ub(a){a=v(a);r(a,function(b){Jb("js",b)})}function Vb(a,b,c){a=v(a);a=Ma(a,function(g){return!!g});var d=[];r(a,function(g){Q[P("js",g)]==void 0&&d.push(g)});var e=!d.length;if(b){var f=Ka(a,n(Gb,null,"js"));e&&f?b():(a=P("js",a.sort().join("|")),nb(a,b))}c&&!e&&c(d)}function Wb(a,b){a=v(a);r(a,function(c){if(c){var d=Xb[c]||c;d=O("js",d);var e=Q[P("js",c)];e&&d!=e&&Yb(c)}});Vb(a,b,Zb)}
function Zb(a){r(a,function(b){function c(){Rb(e,b)}var d=U[b],e=Xb[b]||b;d?Wb(d,c):c()})}function Yb(a){a=v(a);r(a,function(b){var c=[],d;for(d in U){var e=U[d];e=v(e);r(e,function(f){f==b&&c.push(d)})}r(c,function(f){Yb(f)});Sb(b)})}function $b(a,b){Nb("js",a,b)}function ac(a){Pb("js",a)}var U={};"js-d"in x||w("js-d",U);U=x["js-d"];var Xb={};"js-u"in x||w("js-u",Xb);Xb=x["js-u"];function bc(a,b,c){zb("css",a,b,c)}function cc(a,b){Db("css",a,b)}function dc(a){a=v(a);r(a,function(b){Jb("css",b)})};/*

 Copyright 2012-2017 Google Inc. All Rights Reserved.
 Use of this source code is governed by The MIT License.
 SPDX-License-Identifier: MIT
*/
function ec(a,b,c){if(b){b=[];var d=0;c&&(a+="\r\n");var e=a.indexOf("[\r\n",d);for(e>-1&&(d=e+3);(e=a.indexOf(",\r\n",d))>-1;){var f=Pa(a.substring(d,e));d=e+3;f&&b.push(JSON.parse(f))}e=a.indexOf("]\r\n",d);e>-1&&(f=Pa(a.substring(d,e)),d=e+3,f&&b.push(JSON.parse(f)));f="";a.length>d&&(f=a.substring(d),c&&y(f,"\r\n")&&(f=f.substring(0,f.length-2)));b=fc(b);return{F:b,l:f}}a=JSON.parse(a);b=fc(v(a));return{F:b,l:""}}
function V(a,b,c,d){var e=c&&c.type.lastIndexOf("navigate",0)==0,f=c&&c.reverse,g=c&&!!c.position,h=c&&c.s,k=b.name||"",m="process "+N(a),B=!A["experimental-process-async"];var u=0;b.timing||(b.timing={});b.title&&(document.title=b.title);e&&b.url&&N(b.url)!=N(window.location.href)&&ib(b.url+window.location.hash);b.head&&(u=n(function(t,C){t=W(t);gc(t);hc(t);rb(m);ic(t,function(){C.spfProcessHead=q();sb(m,B)})},null,b.head,b.timing),u=J(m,u));b.attr&&(u=n(function(t,C){for(var H in t){var M=document.getElementById(H);
if(M){var R=void 0,lc=t[H];for(R in lc){var va=lc[R];R=="class"?M.className=va:R=="style"?M.style.cssText=va:(M.setAttribute(R,va),R=="value"&&(M[R]=va))}}}C.spfProcessAttr=q()},null,b.attr,b.timing),u=J(m,u));var I=b.body||{},jd=u,Za;for(Za in I)u=n(function(t,C){if(t=document.getElementById(t)){!e||g||h||(w("nav-scroll-position",null),w("nav-scroll-url",null),window.scroll(0,0),h=!0,c&&(c.s=!0));var H=W(C);hc(H);var M=function(){rb(m);ic(H,function(){sb(m,B)})};C=A["animation-class"];jc&&db(t,C)?
(t=new kc(t,H.html,C,k,!!f),rb(m),L(t.key,!0),J(t.key,n(mc,null,t),0),J(t.key,n(nc,null,t),17),J(t.key,n(oc,null,t),t.duration),J(t.key,n(function(){M();sb(m,B)},null),0),L(t.key)):(C=A["experimental-html-handler"])?(rb(m),C(H.html,t,function(){M();sb(m,B)})):(Da(t,Fa(H.html)),M())}},null,Za,I[Za],b.timing),u=J(m,u);I=u-jd;b.foot?(u=n(function(t,C,H){H&&(C.spfProcessBody=q());t=W(t);hc(t);rb(m);ic(t,function(){C.spfProcessFoot=q();sb(m,B)})},null,b.foot,b.timing,I),u=J(m,u)):I&&(u=n(function(t){t.spfProcessBody=
q()},null,b.timing),u=J(m,u));d&&(u=J(m,n(d,null,a,b)));L(m,B)}function pc(a,b,c,d){c="preprocess "+N(a);if(b.head){var e=n(function(h){h=W(h);gc(h);qc(h);rc(h)},null,b.head);J(c,e)}var f=b.body||{},g;for(g in f)f[g]&&(e=n(function(h,k){h=W(k);qc(h);rc(h)},null,g,f[g]),J(c,e));b.foot&&(e=n(function(h){h=W(h);qc(h);rc(h)},null,b.foot),J(c,e));d&&J(c,n(d,null,a,b));L(c)}
function mc(a){E(a.g,a.B);E(a.g,a.L);E(a.g,a.T);E(a.g,a.P);E(a.g,a.S);a.u=document.createElement("div");a.u.className=a.W;var b=a.g,c=a.u;if(c){for(var d;d=b.firstChild;)c.appendChild(d);b.appendChild(c)}a.j=document.createElement("div");a.j.className=a.V;Da(a.j,Fa(a.U));a.reverse?(b=a.u,b.parentNode.insertBefore(a.j,b)):(b=a.u,b.parentNode.insertBefore(a.j,b.nextSibling))}function nc(a){F(a.g,a.P);F(a.g,a.S);E(a.g,a.J);E(a.g,a.K)}
function oc(a){a.g.removeChild(a.u);var b=a.j,c,d=b.parentNode;if(d&&d.nodeType!=11)if(b.removeNode)b.removeNode(!1);else{for(;c=b.firstChild;)d.insertBefore(c,b);d.removeChild(b)}F(a.g,a.J);F(a.g,a.K);F(a.g,a.L);F(a.g,a.T);F(a.g,a.B)}function fc(a){var b=v(a);r(b,function(c){if(c){c.head&&(c.head=W(c.head));if(c.body)for(var d in c.body)c.body[d]=W(c.body[d]);c.foot&&(c.foot=W(c.foot))}});return a}
function W(a){var b=new sc;if(!a)return b;if(!Oa(a))return a.scripts&&r(a.scripts,function(c){b.scripts.push({url:c.url||"",text:c.text||"",name:c.name||"",async:c.async||!1})}),a.styles&&r(a.styles,function(c){b.styles.push({url:c.url||"",text:c.text||"",name:c.name||""})}),a.links&&r(a.links,function(c){c.rel=="spf-preconnect"&&b.links.push({url:c.url||"",rel:c.rel||""})}),b.html=a.html||"",b;a=a.replace(tc,function(c,d,e,f){if(d=="script"){d=(d=e.match(uc))?d[1]:"";var g=e.match(vc);g=g?g[1]:"";
var h=wc.test(e);e=xc.exec(e);return(e=!e||e[1].indexOf("/javascript")!=-1||e[1].indexOf("/x-javascript")!=-1||e[1].indexOf("/ecmascript")!=-1)?(b.scripts.push({url:g,text:f,name:d,async:h}),""):c}return d=="style"&&(d=(d=e.match(uc))?d[1]:"",e=xc.exec(e),e=!e||e[1].indexOf("text/css")!=-1)?(b.styles.push({url:"",text:f,name:d}),""):c});a=a.replace(yc,function(c,d){var e=d.match(zc);e=e?e[1]:"";return e=="stylesheet"?(e=(e=d.match(uc))?e[1]:"",d=(d=d.match(Ac))?d[1]:"",b.styles.push({url:d,text:"",
name:e}),""):e=="spf-preconnect"?(d=(d=d.match(Ac))?d[1]:"",b.links.push({url:d,rel:e}),""):c});b.html=a;return b}function ic(a,b){if(a.scripts.length<=0)b&&b();else{var c=-1,d=function(){c++;if(c<a.scripts.length){var e=a.scripts[c],f=function(){};e.url?f=e.name?n(Rb,null,e.url,e.name):n(Tb,null,e.url):e.text&&(f=e.name?n($b,null,e.text,e.name):n(ac,null,e.text));e.url&&!e.async?f(d):(f(),d())}else b&&b()};d()}}
function rc(a){a.scripts.length<=0||(a=Na(a.scripts,function(b){return b.url}),Ub(a))}function hc(a){a.styles.length<=0||r(a.styles,function(b){b.url?b.name?bc(b.url,b.name):cc(b.url):b.text&&(b.name?Nb("css",b.text,b.name):Pb("css",b.text))})}function qc(a){a.styles.length<=0||(a=Na(a.styles,function(b){return b.url}),dc(a))}function gc(a){a.links.length<=0||(a=Na(a.links,function(b){return b.rel=="spf-preconnect"?b.url:""}),Qb(a))}
function kc(a,b,c,d,e){var f=parseInt(A["animation-duration"],10);this.g=a;this.U=b;this.duration=f;this.reverse=e;b=document.body;b=(b.dataset?b.dataset.spfName:b.getAttribute("data-"+Qa()))||"";f=parseInt(x.uid,10)||0;f++;this.key=a["spf-key"]||(a["spf-key"]=""+w("uid",f));this.L=b&&c+"-from-"+b;this.T=d&&c+"-to-"+d;this.u=null;this.W=c+"-old";this.j=null;this.V=c+"-new";this.B=c+(e?"-reverse":"-forward");this.P=c+"-start";this.S=this.B+"-start";this.J=c+"-end";this.K=this.B+"-end"}
function sc(){this.html="";this.scripts=[];this.styles=[];this.links=[]}
var jc=function(){var a=document.createElement("div");return"transition"in a.style?!0:La(["webkit","Moz","Ms","O","Khtml"],function(b){return b+"Transition"in a.style})}(),yc=/\x3clink([\s\S]*?)\x3e/ig,tc=/\x3c(script|style)([\s\S]*?)\x3e([\s\S]*?)\x3c\/\1\x3e/ig,wc=/(?:\s|^)async(?:\s|=|$)/i,Ac=/(?:\s|^)href\s*=\s*["']?([^\s"']+)/i,uc=/(?:\s|^)name\s*=\s*["']?([^\s"']+)/i,zc=/(?:\s|^)rel\s*=\s*["']?([^\s"']+)/i,vc=/(?:\s|^)src\s*=\s*["']?([^\s"']+)/i,xc=/(?:\s|^)type\s*=\s*["']([^"']+)["']/i;function Bc(a,b,c,d){var e=d||{},f=!1,g=0,h,k=new XMLHttpRequest;k.open(a,b,!0);k.timing={};var m=k.abort;k.abort=function(){clearTimeout(h);k.onreadystatechange=null;m.call(k)};k.onreadystatechange=function(){var u=k.timing;if(k.readyState==2){u.responseStart=u.responseStart||q();if(k.responseType=="json")f=!1;else if(A["assume-all-json-requests-chunked"]||(k.getResponseHeader("Transfer-Encoding")||"").toLowerCase().indexOf("chunked")>-1)f=!0;else{u=k.getResponseHeader("X-Firefox-Spdy");var I=window.chrome&&
chrome.loadTimes&&chrome.loadTimes();I=I&&I.wasFetchedViaSpdy;f=!(!u&&!I)}e.N&&e.N(k)}else k.readyState==3?f&&e.C&&(u=k.responseText.substring(g),g=k.responseText.length,e.C(k,u)):k.readyState==4&&(u.responseEnd=u.responseEnd||q(),window.performance&&window.performance.getEntriesByName&&(k.resourceTiming=window.performance.getEntriesByName(b).pop()),f&&e.C&&k.responseText.length>g&&(u=k.responseText.substring(g),g=k.responseText.length,e.C(k,u)),clearTimeout(h),e.M&&e.M(k))};"responseType"in k&&e.responseType==
"json"&&(k.responseType="json");e.withCredentials&&(k.withCredentials=e.withCredentials);d="FormData"in window&&c instanceof FormData;a=a=="POST"&&!d;if(e.headers)for(var B in e.headers)k.setRequestHeader(B,e.headers[B]),"content-type"==B.toLowerCase()&&(a=!1);a&&k.setRequestHeader("Content-Type","application/x-www-form-urlencoded");e.R>0&&(h=setTimeout(function(){k.abort();e.O&&e.O(k)},e.R));k.timing.fetchStart=q();k.send(c);return k};function Cc(a,b){b=b||{};b.method=((b.method||"GET")+"").toUpperCase();b.type=b.type||"request";var c=a,d=A["url-identifier"]||"";if(d){d=d.replace("__type__",b.type||"");var e=z(c,"#"),f=z(e[0],"?");c=f[0];var g=f[1];f=f[2];var h=e[1];e=e[2];if(d.lastIndexOf("?",0)==0)g&&(d=d.replace("?","&")),f+=d;else{if(d.lastIndexOf(".",0)==0)if(y(c,"/"))d="index"+d;else{var k=c.lastIndexOf(".");k>-1&&(c=c.substring(0,k))}else y(c,"/")&&d.lastIndexOf("/",0)==0&&(d=d.substring(1));c+=d}c=c+g+f+h+e}d=N(c);c={};
c.spfUrl=d;c.startTime=q();c.fetchStart=c.startTime;g=Dc(a,b.current,null,b.type,!1);g=Ec(g,b.current);c.spfPrefetched=!!g&&g.type=="prefetch";c.spfCached=!!g;if(g){a=n(Fc,null,a,b,c,g.key,g.response);b=window._spf_state=window._spf_state||{};var m=parseInt(b.uid,10)||0;m++;b=b.uid=m;Ta[b]=a;Wa?window.postMessage("spf:"+b,"*"):window.setTimeout(n(Sa,null,b),0);return null}g={};if(f=A["request-headers"])for(m in f)h=f[m],g[m]=h==null?"":String(h);if(b.headers)for(m in b.headers)h=b.headers[m],g[m]=
h==null?"":String(h);b.i!=null&&(g["X-SPF-Referer"]=b.i);b.current!=null&&(g["X-SPF-Previous"]=b.current);if(m=A["advanced-header-identifier"])g["X-SPF-Request"]=m.replace("__type__",b.type),g.Accept="application/json";m=new Gc;f=n(Hc,null,a,b,c,m);a={headers:g,R:A["request-timeout"],N:n(Ic,null,a,m),C:n(Jc,null,a,b,c,m),M:f,O:f};b.withCredentials&&(a.withCredentials=b.withCredentials);A["advanced-response-type-json"]&&(a.responseType="json");return b.method=="POST"?Bc("POST",d,b.H,a):Bc("GET",d,
null,a)}function Fc(a,b,c,d,e){var f=!1;c.responseStart=c.responseEnd=q();b.type&&b.type.lastIndexOf("navigate",0)==0&&(c.navigationStart=c.startTime,A["cache-unified"]||(Ya(d),f=!0));b.o&&e.type=="multipart"&&r(e.parts,function(g){g.timing||(g.timing={});g.timing.spfCached=!!c.spfCached;g.timing.spfPrefetched=!!c.spfPrefetched;b.o(a,g)});Kc(a,b,c,e,f)}function Ic(a,b,c){a=c.getResponseHeader("X-SPF-Response-Type")||"";b.j=a.toLowerCase().indexOf("multipart")!=-1}
function Jc(a,b,c,d,e,f,g){if(d.j){f=d.l+f;try{var h=ec(f,!0,g)}catch(k){e.abort();b.m&&b.m(a,k,e);return}b.o&&r(h.F,function(k){k.timing||(k.timing={});k.timing.spfCached=!!c.spfCached;k.timing.spfPrefetched=!!c.spfPrefetched;b.o(a,k)});d.g=d.g.concat(h.F);d.l=h.l}}
function Hc(a,b,c,d,e){if(e.timing)for(var f in e.timing)c[f]=e.timing[f];if(e.resourceTiming)if(b.type=="load")for(var g in e.resourceTiming)c[g]=e.resourceTiming[g];else if(window.performance&&window.performance.timing&&(f=window.performance.timing.navigationStart,f+e.resourceTiming.startTime>=c.startTime))for(var h in e.resourceTiming)g=e.resourceTiming[h],g!==void 0&&(y(h,"Start")||y(h,"End")||h=="startTime")&&(c[h]=f+Math.round(g));b.type!="load"&&(c.navigationStart=c.startTime);d.g.length&&
(d.l=Pa(d.l),d.l&&Jc(a,b,c,d,e,"",!0));if(e.responseType=="json"){if(!e.response){b.m&&b.m(a,Error("JSON response parsing failed"),e);return}var k=fc(v(e.response))}else try{k=ec(e.responseText).F}catch(B){b.m&&b.m(a,B,e);return}if(b.o&&k.length>1)for(d=d.g.length;d<k.length;d++)e=k[d],e.timing||(e.timing={}),e.timing.spfCached=!!c.spfCached,e.timing.spfPrefetched=!!c.spfPrefetched,b.o(a,e);if(k.length>1){var m;r(k,function(B){B.cacheType&&(m=B.cacheType)});k={parts:k,type:"multipart"};m&&(k.cacheType=
m)}else k=k.length==1?k[0]:{};Kc(a,b,c,k,!0)}function Kc(a,b,c,d,e){if(e&&b.method!="POST"&&(e=Dc(a,b.current,d.cacheType,b.type,!0))){d.cacheKey=e;var f={response:d,type:b.type||""},g=parseInt(A["cache-lifetime"],10),h=parseInt(A["cache-max"],10);g<=0||h<=0||(h=D(),f={data:f,life:g,time:q(),count:0},bb(f),h[e]=f,setTimeout($a,1E3))}d.timing=c;b.D&&b.D(a,d)}
function Dc(a,b,c,d,e){a=N(a);var f;A["cache-unified"]?f=a:d=="navigate-back"||d=="navigate-forward"?f="history "+a:d=="navigate"?f=(e?"history ":"prefetch ")+a:d=="prefetch"&&(f=e?"prefetch "+a:"");b&&c=="url"?f+=" previous "+b:b&&c=="path"&&(f+=" previous "+wb(b).pathname);return f||""}
function Ec(a,b){var c=[];b&&(c.push(a+" previous "+b),c.push(a+" previous "+wb(b).pathname));c.push(a);var d=null;La(c,function(e){a:{var f=D();if(e in f){f=f[e];if(ab(f)){bb(f);f=f.data;break a}Ya(e)}f=void 0}f&&(d={key:e,response:f.response,type:f.type});return!!f});return d}function Gc(){this.j=!1;this.l="";this.g=[]};function Lc(a){return gb(a,function(b){return db(b,A["link-class"])})}function Mc(a){return gb(a,function(b){return db(b,A["nolink-class"])})}function Nc(a,b){return gb(a,function(c){return c.href&&c.tagName.toLowerCase()!="img"},b)}function Oc(a){if(a.metaKey||a.altKey||a.ctrlKey||a.shiftKey||a.button>0)return null;var b=Lc(a.target);return!b||A["nolink-class"]&&Mc(a.target)?null:(a=Nc(a.target,b))?a.href:null}function Pc(a){return wb(a).origin!=wb(window.location.href).origin?!1:!0}
function Qc(){if(!x["nav-init"])return!1;var a=parseInt(x["nav-counter"],10)||0;a++;var b=parseInt(A["navigate-limit"],10);b=isNaN(b)?Infinity:b;if(a>b)return!1;a=parseInt(x["nav-init-time"],10);a--;a=q()-a;b=parseInt(A["navigate-lifetime"],10);b=isNaN(b)?Infinity:b;return a>b?!1:!0}function Rc(a,b){b=b||window.location.href;return a.indexOf("#")!=-1&&(a=N(a),b=N(b),a==b)?!1:!0}
function Sc(a){if(!a.defaultPrevented){var b=Oc(a);b&&(b=yb(b),Pc(b)&&Qc()&&p("spfclick",{url:b,target:a.target})&&(Tc(b,{},new Uc),a.preventDefault()))}}function Vc(a){var b=Oc(a);b&&setTimeout(function(){Wc(b)},0)}function Xc(){var a=x["nav-scroll-position"]||null;var b=x["nav-scroll-url"]||"";a=a&&b==window.location.href?a:null;Yc();a&&window.scroll.apply(null,a)}
function Zc(a,b){b=new Uc({current:b&&b["spf-current"],history:!0,position:b&&b["spf-position"],i:b&&b["spf-referer"],reverse:!(!b||!b["spf-back"])});var c=A["reload-identifier"];c&&(a=xb(a,[c]));Pc(a)?Qc()?p("spfhistory",{url:a,referer:b.i,previous:b.current})&&(b.position&&(w("nav-scroll-position",[window.pageXOffset,window.pageYOffset]),w("nav-scroll-url",window.location.href)),Tc(a,{},b)):X(a,"1"):X(a,"9")}
function Tc(a,b,c){$c();if(Rc(a,c.current))if(ad(a,c.i,c.current,b)){w("nav-counter",(parseInt(x["nav-counter"],10)||0)+1);bd(a);var d=N(a),e="preprocess "+N(d);for(f in K)e!=f&&f.lastIndexOf("preprocess",0)==0&&tb(f);d=cd()[d];w("nav-request",d);w("nav-promote",null);w("nav-promote-time",null);if(d&&d.readyState!=4)d="preprocess "+N(a),e="promote "+N(a),w("nav-promote",a),w("nav-promote-time",q()),tb(d),L(e,!0),c.history||dd(a,c.i,n(Y,null,b));else{d=n(Y,null,b);e=n(ed,null,b,c);var f=n(fd,null,
b,c);A["advanced-navigate-persist-timing"]||gd();c.type="navigate";c.history&&(c.type+=c.reverse?"-back":"-forward");b=Cc(a,{method:b.method,headers:b.headers,o:e,m:d,D:f,H:b.postData,type:c.type,current:c.current,i:c.i});w("nav-request",b);c.history||dd(a,c.i,d)}}else X(a,"2");else c.history||dd(a,c.i,n(Y,null,b)),hd(a,c)}
function hd(a,b){if(b.position)Yc(),window.scroll.apply(null,b.position),b.s=!0;else if(a=z(a,"#"),a[2]){if(a=document.getElementById(a[2]))Yc(),a.scrollIntoView(),b.s=!0}else b.s||(Yc(),window.scroll(0,0),b.s=!0)}function dd(a,b,c){try{ib(null,{"spf-position":[window.pageXOffset,window.pageYOffset]}),N(a,!0)!=window.location.href&&jb(!1,a,{"spf-referer":b})}catch(d){$c(),c(a,d)}}function Y(a,b,c,d){w("nav-request",null);id(b,c,a,void 0,d)&&X(b,"10",c)}
function ed(a,b,c,d){if(kd(c,d,a))if(d.reload)X(c,"5");else if(d.redirect)ld(a,d.redirect);else try{V(c,d,b,function(){md(c,d,a)})}catch(e){Y(a,c,e)}else X(c,"3")}
function fd(a,b,c,d){w("nav-request",null);if(x["nav-promote"]==b.h){var e=d.timing||{};e.navigationStart=x["nav-promote-time"];e.spfPrefetched=!0}var f=d.type=="multipart";if(!f){if(!nd(c,d,a)){X(c,"4");return}if(d.reload){X(c,"5");return}if(d.redirect){ld(a,d.redirect);return}}try{V(c,f?{}:d,b,function(){var g=d.name||"";f&&r(d.parts,function(h){g=h.name||g});eb(g);hd(c,b);od(c,d,a)})}catch(g){Y(a,c,g)}}function ld(a,b){try{b+=window.location.hash,ib(b,null,!0)}catch(c){$c(),Y(a,b,c)}}
function $c(){var a=x["nav-request"];a&&(a.abort(),w("nav-request",null))}function Z(a,b){if(a){var c=Array.prototype.slice.call(arguments);c[0]=a;c=Ia.apply(null,c)}return c!==!1}
function X(a,b,c){c=c?c.message:"";$c();bd();var d=b;c&&(d+=" Message: "+c);p("spfreload",{url:a,reason:d});var e=window.location.href;A["experimental-remove-history"]&&e==a&&(w("history-ignore-pop",!0),window.history.back());setTimeout(function(){var f=A["reload-identifier"];if(f){var g={};g[f]=encodeURIComponent(b);f=a;var h=z(f,"#");f=h[0];var k=f.indexOf("?")!=-1?"&":"?",m;for(m in g)f+=k+m,g[m]&&(f+="="+g[m]),k="&";a=f+h[1]+h[2]}window.location.href=a;Rc(a,e)||window.location.reload()},0)}
function pd(a,b,c){c.h=c.h||a;if(ad(a,void 0,void 0,b,!0)){var d=n(qd,null,!1,b,c),e=n(rd,null,!1,b,c),f=n(sd,null,!1,b,c);c.type="load";Cc(a,{method:b.method,headers:b.headers,o:e,m:d,D:f,H:b.postData,type:c.type,withCredentials:b.withCredentials})}}function Wc(a,b){a=yb(a);td(a,b||{},new Uc)}
function td(a,b,c){c.h=c.h||a;if(ad(a,void 0,void 0,b,!0)){var d=n(qd,null,!0,b,c),e=n(rd,null,!0,b,c),f=n(sd,null,!0,b,c);c.type="prefetch";b=Cc(a,{method:b.method,headers:b.headers,o:e,m:d,D:f,H:b.postData,type:c.type,current:c.current});a=N(a);cd()[a]=b}}function qd(a,b,c,d,e){a&&ud(d);a&&x["nav-promote"]==c.h?Y(b,d,e):id(d,e,b,!0)}
function rd(a,b,c,d,e){if(kd(d,e,b,!0)){if(e.reload){if(!a)return;if(x["nav-promote"]==c.h){X(d,"5");return}}if(e.redirect)vd(a,b,c,e.redirect);else{if(a){var f=n(ed,null,b,c,d,e),g="promote "+N(c.h);J(g,f);if(x["nav-promote"]==c.h){L(g,!0);return}}(a?pc:V)(d,e,c,function(){md(d,e,b,!0)})}}}
function sd(a,b,c,d,e){var f=e.type=="multipart";if(!f){if(!nd(d,e,b,!0)){X(d,"4");return}if(e.reload){if(!a)return;if(x["nav-promote"]==c.h){X(d,"5");return}}if(e.redirect){vd(a,b,c,e.redirect);return}}var g="promote "+N(c.h);if(a){ud(d);if(x["nav-promote"]==c.h){J(g,n(fd,null,b,c,d,e));L(g,!0);return}tb(g)}g=a?pc:V;try{g(d,f?{}:e,c,function(){od(d,e,b,!0)})}catch(h){qd(a,b,c,d,h)}}
function vd(a,b,c,d){a=a?td:pd;var e={};r("onError onRequest onPartProcess onPartDone onProcess onDone".split(" "),function(f){e[f]=b[f]});a(d,e,c)}function id(a,b,c,d,e){a={url:a,err:b,xhr:e};(c=Z((c||{}).onError,a))&&!d&&(c=p("spferror",a));return c}function ad(a,b,c,d,e){a={url:a,referer:b,previous:c};(d=Z((d||{}).onRequest,a))&&!e&&(d=p("spfrequest",a));return d}function kd(a,b,c,d){a={url:a,part:b};(c=Z((c||{}).onPartProcess,a))&&!d&&(c=p("spfpartprocess",a));return c}
function md(a,b,c,d){a={url:a,part:b};Z((c||{}).onPartDone,a)&&!d&&p("spfpartdone",a)}function nd(a,b,c,d){a={url:a,response:b};(c=Z((c||{}).onProcess,a))&&!d&&(c=p("spfprocess",a));return c}function od(a,b,c,d){a={url:a,response:b};Z((c||{}).onDone,a)&&!d&&p("spfdone",a)}function ud(a){a=N(a);var b=cd(),c=b[a];c&&c.abort();delete b[a]}function bd(a){var b=cd();a=a&&N(a);for(var c in b)a!=c&&ud(c)}
var gd,wd=window.performance&&(window.performance.clearResourceTimings||window.performance.webkitClearResourceTimings||window.performance.mozClearResourceTimings||window.performance.msClearResourceTimings||window.performance.oClearResourceTimings);gd=wd?n(wd,window.performance):Ja;function cd(){return"nav-prefetches"in x?x["nav-prefetches"]:w("nav-prefetches",{})}function Yc(){w("nav-scroll-position",null);w("nav-scroll-url",null)}
function Uc(a){a=a||{};this.current=a.history&&a.current?a.current:window.location.href;this.history=!!a.history;this.h=a.h||"";this.position=a.position||null;this.i=a.i!=void 0?a.i:window.location.href;this.reverse=!!a.reverse;this.s=!!a.s;this.type=a.type||""};function xd(){Ib("js");Ib("css");document.readyState=="complete"&&(document.removeEventListener?document.removeEventListener("DOMContentLoaded",xd,!1):document.detachEvent&&document.detachEvent("onreadystatechange",xd))}document.addEventListener?document.addEventListener("DOMContentLoaded",xd,!1):document.attachEvent&&document.attachEvent("onreadystatechange",xd);xd();
var yd={init:function(a){var b=!(typeof window.history.pushState!="function"&&!lb().contentWindow.history.pushState);a=a||{};for(var c in Xa)A[c]=c in a?a[c]:Xa[c];for(c in a)c in Xa||(A[c]=a[c]);if(b){c=id;if(!x["history-init"]&&window.addEventListener){a=window.location.href;window.addEventListener("popstate",mb,!1);w("history-init",!0);w("history-callback",Zc);w("history-error-callback",c);w("history-listener",mb);w("history-url",a);w("history-timestamp",q());var d={"spf-referer":document.referrer};
try{ib(a,d)}catch(e){c&&c(a,e)}}!x["nav-init"]&&document.addEventListener&&(w("nav-init",!0),w("nav-init-time",q()),w("nav-counter",0),document.addEventListener("click",Sc,!1),w("nav-listener",Sc),!A["experimental-prefetch-mousedown"]||"ontouchstart"in window||window.navigator.maxTouchPoints>0||window.navigator.msMaxTouchPoints>0||(document.addEventListener("mousedown",Vc,!1),w("nav-mousedown-listener",Vc)),document.addEventListener("scroll",Xc,!1),w("nav-scroll-listener",Xc))}return b},dispose:function(){typeof History!=
"undefined"&&History.prototype.pushState&&($c(),x["nav-init"]&&(document.removeEventListener&&(document.removeEventListener("click",x["nav-listener"],!1),document.removeEventListener("mousedown",x["nav-mousedown-listener"],!1),document.removeEventListener("scroll",x["nav-scroll-listener"],!1)),w("nav-listener",null),w("nav-mousedown-listener",null),w("nav-scroll-listener",null),w("nav-scroll-position",null),w("nav-scroll-url",null),w("nav-init",!1),w("nav-init-time",null),w("nav-counter",null)),x["history-init"]&&
(window.removeEventListener&&window.removeEventListener("popstate",x["history-listener"],!1),w("history-init",!1),w("history-callback",null),w("history-error-callback",null),w("history-listener",null),w("history-url",null),w("history-timestamp",0)));for(var a in A)delete A[a]},navigate:function(a,b){a&&(a=yb(a),Pc(a)?Qc()?Tc(a,b||{},new Uc):X(a,"1"):X(a,"9"))},load:function(a,b){a=yb(a);pd(a,b||{},new Uc)},prefetch:Wc,process:function(a,b){function c(f,g,h,k){f==g&&b&&b(k)}var d=window.location.href;
if(a.type=="multipart"){a=a.parts;var e=a.length-1;r(a,function(f,g){V(d,f,null,n(c,null,g,e))})}else V(d,a,null,n(c,null,0,0))}},zd={cache:{remove:Ya,clear:function(){D({})}},script:{load:Rb,get:Tb,ready:Vb,done:function(a){Q[P("js",a)]="";Bb("js")},require:Wb,declare:function(a,b){if(a){for(var c in a)U[c]=a[c];if(b)for(c in b)Xb[c]=b[c]}},path:function(a){w("rsrc-p-js",a)},unload:Sb,ignore:function(a,b){a=v(a);a=P("js",a.sort().join("|"));ob(a,b)},unrequire:Yb,prefetch:Ub},style:{load:bc,get:cc,
unload:function(a){Eb("css",a)},path:function(a){w("rsrc-p-css",a)},prefetch:dc}},l=this;l.spf=l.spf||{};var Ad=l.spf,Bd;for(Bd in yd)Ad[Bd]=yd[Bd];for(var Cd in zd)for(var Dd in zd[Cd])Ad[Cd]=Ad[Cd]||{},Ad[Cd][Dd]=zd[Cd][Dd];p("spfready");}).call(this);
